# .travis.yml
sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "dokyung0930@naver.com"
  - git config --global user.name "dokongg"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "V7/992BZeQzaJ4ZP+Dg+NzCmjOIHlyFCoe2E9Cjmz/M9GWbs2PNUSVhN+Y+Yi1DHIXad2LLX3bh68WT+sdhYVSsCgOvcjw2qAOnl9ID04TD0+CiRZc0sT8yuLPDmy9wWHTTND4Mw/TWCruwqsXJpcpoO44og0xQCgEuvXPOINGv11Q8F56ajTXMsR6Y/Z1exZ3ROi+8lRn1jqRA2+5HIjOtM0QQSgQmkYcAjCnpUZLeX170wYmq6FpLfRR4e12iRClzrMpLHR+4nYWqypJv8jwHO+hpjxNaLN9TD2QPgi2pOwAnRB6+sMDyUOPjyYV8B/8UWbnNostBia+duG74XEzWjyAlhRSMzLAefuLEq3ebPCN+1RDts3qtB0CszpJRyryYMf+p3o+T1LP//o/VqZk2NKG+1zcLWT4AkG+4AnmZE1vb56N3yB5uSwDH4ftzcrKJUC/RV+Mt0vNWMMOXz0oeby02BGzv/CZ67zxrOoOOjvK9WYk3tMJ+zGN+gmpiYwoVGZFbxEDcFqr6K7urMhoknNyNCtQUQrrpsHzVoVlvgf1/i5+1nNuF9jiC+hfNwzRj4Zd9yjnGdnXFWZnG27ofj2xDfT3NKtaIBEoSltQHkwMJ9L0tSqMP8DZrPuYT/SIOyWyFntjqWvI6n5fbbCK79VOnQePS/j+cmcfMprsg="
branches:
  only:
    - master
