# _config.yml
# for Travis CI. (shit custom gem api...) ##################
destination: ./exampleoutputname

production_url: https://dokongg.github.io/
source_url: https://github.com/dokongg/blog-management

safe: False
lsi: False

username: dokongg
repo: blog-management
branch: master
############################################################